### ISSUE TITLE
Using matchlist api and can't hit requests more than 5!

### ISSUE THREAD

**Issue by musaghauri** [paquettg/leaguewrap#129]
Hi, I am using matchlist api! I am doing development and need to hit requests every minute! But I am not able to do it as it there is a limit to number of requests. There is some concept of memcached and limit! I installed memcached as a service but still facing the problem! I am using windows and xampp fr development!

**Comment by musaghauri** [comment]
I think I am having issue with memcache! Don't know how to install memcache! Can you guide me what are the prereqs to run matchlist endpoint smoothly?

**Comment by dnlbauer** [comment]
Unfortunately fixing your configuration is out of scope of this api. Please
ask in the memcached support pipelines for that.

What errors are you getting from the match endpoint? If it's 429 this is
because the endpoint is heavily throttling atm because of season start.

Muhammad Musa <notifications@github.com> schrieb am So., 11. Dez. 2016,
15:56:

**Comment by musaghauri** [comment]
![screenshot 2016-12-11 20 10 00](https://cloud.githubusercontent.com/assets/13300306/21080957/e53fce86-bfdd-11e6-902d-43fdccbb198a.png)

See this is the problem! Sometimes I get the result but most of the times I get this error!

**Comment by dnlbauer** [comment]
This is not an error in the library and also not an error in your code.
Getting a 429 without a response header means the underlying service at
riot is throttling because there are too many requests from too many people.

Riot is aware of that issue and they are working on that. It's most likely
gone in a few days when the stress from season start is gone.

#Closed.

Muhammad Musa <notifications@github.com> schrieb am So., 11. Dez. 2016,
16:11:
