### ISSUE TITLE
Problem with observers->encriptionKey

### ISSUE THREAD

**Issue by pabliito07** [paquettg/leaguewrap#72]
Hi, i continue working with this api, and now i get a problem with the function 
$game->observers->encriptionKey. When i try this, it return an empty print. What i am doing wrong? Thanks!

$summoner = $api->summoner();     
$currentGame = $api->currentGame();
$invocador1 = $summoner->info(43699) ;
$game = $currentGame->currentGame($invocador1->id);
 print_r ($game->observers->encriptionKey);

**Comment by KioCoan** [comment]
It only works if the spectator for the region that you are trying is working for the queue that you are trying to get. 

Since your var ir called 'invocador1' I assume that you are trying to get the current game in Brazil. If I remember, the spectator is only working for ranked games atm in this server.

**Comment by danijoo** [comment]
Yes. Spectator mode for brazil had some serious problem over the last few months. This should be fixed now and the above code should give a valid result .
