### ISSUE TITLE
NoValidLimitInterfaceException on creating api

### ISSUE THREAD

**Issue by archer3cl** [paquettg/leaguewrap#76]
Hi im just trying to use your wraper but im only putting this lines

```php
        $this->api = new Api($mykey);
        $this->api->setRegion('lan');
        $this->api->limit(10, 10);
        $this->api->limit(500, 600);
```

and im getting this error

**NoValidLimitInterfaceException** in **Api.php** line 266:
We could not load a valid limit interface.

Could you help me?

**Comment by danijoo** [comment]
Looks like a permission issue to me. If you track this down, this Exception is thrown if FileLimit#isValid()  returns false. This is the case when its not possible to write to the file system. 

The Limit system of the api tries first to use memcached. If memcached is not installed, it will use use file to log api calls in order to calculate if limit is reached. If this is also not possible, you get this error.

**Comment by archer3cl** [comment]
Well, seems like my dev environment didn't have memcached recognized. Thanks for your help
