### ISSUE TITLE
Is there any to update this repo so i can use it with laravel 5 ?

### ISSUE THREAD

**Issue by minedun6** [paquettg/leaguewrap#80]
The problem is that there is a wrapper of this repo for laravel 4 but since most of my work is with L5 and it tells me that it needs guzzle 0.6 so i can't even require the repo, is there any way to help plz ^^ ?
This is really urgent.

**Comment by danijoo** [comment]
I never used laravel, so can you please give a more in depth explanation what the problem is?
Is it because laravel requires a different version of guzzle that is incompatible with leaguewrap?

**Comment by minedun6** [comment]
yes my friend, currently this package uses guzzle 0.4 !!
and laravel 5 requires guzzle 0.6 and higher so it's annyoing a bit but i need to use it in a project ^^

**Comment by danijoo** [comment]
Its version 4.0 and 6.0, not 0.4 :)
But yes. It should be possible to update guzzle to a more recent version. It shouldnt be too much work to change the client to use it. Maybe I have the time later this day.
Until then, you could clone the project from git and include it manually with a custom Client implementation by extending ClientInterface.php

**Comment by danijoo** [comment]
The problem is that guzzle 6.x requires php version 5.5+ while this api lists php 5.4 under supported versions. I agree that not supporting laravel 5 is bad, but dropping support for php 5.4 is a big step. Lets see what @paquettg says about that since he is the actual owner of this project.

For now I created a seperate branch [guzzle6](/paquettg/leaguewrap/tree/guzzle6) that uses guzzle version ~6.0 and should work with laravel 5. Feel free to use that branch until then.

**Comment by minedun6** [comment]
how can i update my composer file to make use of this branch ?

**Comment by mth3n** [comment]
Modify you composer.json to make the code snippet below and run sudo composer update.

"repositories": [
        {
            "type": "git",
            "url": "https://github.com/paquettg/leaguewrap"
        }
    ],
    "require": {
        "paquettg/leaguewrap": "dev-guzzle6"
    }

**Comment by acupajoe** [comment]
@danijoo Thank you for the update!
